#!/usr/bin/env bash
# build-fragment.sh — regenerate examples/ssh-bypass/manifest-fragment.yaml from the
# canonical recipe source artifact (hooks/block-ssh-bypass.sh).
#
# The manifest fragment is self-contained (a user copies it into tools.yaml and
# runs `rc build` with ZERO rc source edits). The recipe provisions the
# block-ssh-bypass.sh hook root-owned at its dest path via a single-line,
# base64-encoded install_cmd (injection-safe — no newlines reach the Dockerfile).
#
# This generator exists only so the artifact stays human-readable/editable in
# version control; the COMMITTED manifest-fragment.yaml is the load-bearing,
# copy-pasteable recipe. Re-run this after editing the source artifact:
#   examples/ssh-bypass/build-fragment.sh > examples/ssh-bypass/manifest-fragment.yaml
#
# rip-cage-wlwc.11 (block-ssh-bypass hook demoted from base image to recipe;
# ADR-025 D2 / ADR-026 D2 — command-string guard is composable, not floor).
set -euo pipefail

_here="$(cd "$(dirname "$0")" && pwd)"
_root="$(cd "${_here}/../.." && pwd)"

b64() { base64 < "$1" | tr -d '\n'; }

HOOK_B64="$(b64 "${_root}/hooks/block-ssh-bypass.sh")"

cat <<YAML
version: 1
# ssh-bypass (block-ssh-bypass hook) — composable TOOL recipe (rip-cage-wlwc.11).
#
# The block-ssh-bypass PreToolUse hook is NOT floor (ADR-025 D2, ADR-026 D2) — it is
# a composable command-string guard recipe. To enable it in your cage, copy the
# tools[] entry below into ~/.config/rip-cage/tools.yaml, run \`rc build\`, then
# register the hook via the CC PreToolUse settings fragment (settings-fragment.json
# in this directory). No rc source edits required.
#
# What this recipe provisions:
#   ssh-bypass-hook (install_cmd) — writes /usr/local/lib/rip-cage/hooks/block-ssh-bypass.sh
#   root:root mode 0755 at build time so the agent cannot overwrite or disable it.
#
# What this recipe does NOT touch:
#   The known_hosts floor (COPY ssh/known_hosts.github, COPY ssh/ssh_config) is welded
#   in the base image and is ADR-022's domain — it is a distinct layer from this hook.
#   This recipe only covers the CLI-flag command-string guard (the ssh -o flag class).
#
# How it works in the cage:
#   The CC PreToolUse hook in settings-fragment.json invokes block-ssh-bypass.sh for
#   every Bash tool call. The script checks for ssh-family commands that carry
#   host-key-override flags (-o UserKnownHostsFile, -o GlobalKnownHostsFile,
#   -o StrictHostKeyChecking=accept-new/no/off) and denies them with a helpful
#   message pointing to .rip-cage.yaml ssh.allowed_hosts (ADR-022 D5).
#
# Agentic composition model (ADR-005 D12, "built for the agentic era"):
#   1. Copy the tools[] entry below into ~/.config/rip-cage/tools.yaml.
#   2. Run \`rc build\`.
#   3. Register the PreToolUse hook: merge settings-fragment.json into your
#      ~/.claude/settings.json (or the workspace .claude/settings.json).
#   No installer, no auto-wire mechanism, no rc source edit required.
#
# GENERATED by examples/ssh-bypass/build-fragment.sh from the canonical source artifact
# (hooks/block-ssh-bypass.sh). Do not hand-edit the base64 blob — edit the source file
# and re-run the generator.
#
# egress: [] — block-ssh-bypass opens zero external connections (local guard only).

tools:
  # ---------------------------------------------------------------------------
  # TOOL entry: provision block-ssh-bypass.sh hook root-owned at its dest path.
  # install_cmd runs as root in the runtime stage (RUN). It:
  #   - creates /usr/local/lib/rip-cage/hooks/ if absent,
  #   - writes /usr/local/lib/rip-cage/hooks/block-ssh-bypass.sh (the hook script),
  #     root:root mode 0755 — agent can execute but cannot overwrite or disable it.
  # No apt packages needed; the leading ':' is a no-op so the rc-generated
  # 'apt-get update && <install_cmd> && rm ...' wrapper stays valid.
  - name: ssh-bypass-hook
    archetype: TOOL
    version_pin: "bundled-recipe"
    install_cmd: ": && mkdir -p /usr/local/lib/rip-cage/hooks && echo '${HOOK_B64}' | base64 -d > /usr/local/lib/rip-cage/hooks/block-ssh-bypass.sh && chown root:root /usr/local/lib/rip-cage/hooks/block-ssh-bypass.sh && chmod 0755 /usr/local/lib/rip-cage/hooks/block-ssh-bypass.sh"
    egress: []
    mounts: []
YAML
