#!/usr/bin/env bash
# build-fragment.sh — regenerate examples/dcg/manifest-fragment.yaml from the
# canonical recipe source artifacts (dcg/dcg-guard, dcg/default-config.toml,
# tests/fixtures/ripcage-testsentinel-rule.yaml, examples/dcg/smoke.sh).
#
# The manifest fragment is self-contained (a user copies it into tools.yaml and
# runs `rc build` with ZERO rc source edits). The recipe provisions the dcg engine
# (guard wrapper + cage config + sentinel fixture) root-owned at their dest paths
# via a single-line, base64-encoded install_cmd (injection-safe — no newlines
# reach the Dockerfile).
#
# Also installs the recipe's behavioral smoke test into the recipe-tests dir
# (/usr/local/lib/rip-cage/recipe-tests/dcg-smoke.sh) as root:root so the
# generic name-free runner (run-recipe-smokes.sh) can run it (ADR-027 D1).
#
# This generator exists only so the artifacts stay human-readable/editable in
# version control; the COMMITTED manifest-fragment.yaml is the load-bearing,
# copy-pasteable recipe. Re-run this after editing any source artifact:
#   examples/dcg/build-fragment.sh > examples/dcg/manifest-fragment.yaml
#
# rip-cage-wlwc.10 (dcg engine demoted from base image to recipe; ADR-025 D2/D3).
set -euo pipefail

_here="$(cd "$(dirname "$0")" && pwd)"
_root="$(cd "${_here}/../.." && pwd)"

b64() { base64 < "$1" | tr -d '\n'; }

GUARD_B64="$(b64 "${_root}/dcg/dcg-guard")"
CONFIG_B64="$(b64 "${_root}/dcg/default-config.toml")"
SENTINEL_B64="$(b64 "${_root}/tests/fixtures/ripcage-testsentinel-rule.yaml")"
SMOKE_B64="$(b64 "${_here}/smoke.sh")"

cat <<YAML
version: 1
# DCG (Destructive Command Guard) — composable from-source TOOL recipe (rip-cage-wlwc.10).
#
# DCG is NOT floor (ADR-025 D2, ADR-026 D2) — it is a composable command-guard recipe.
# To enable DCG in your cage, copy these entries into ~/.config/rip-cage/tools.yaml and
# run \`rc build\`. No rc source edits required; this composes via the existing TOOL
# archetype + from-source build + install_cmd wiring (ADR-005 D12).
#
# What this recipe provisions:
#   1. dcg (build_source) — builds the \`dcg\` binary from source in an isolated Rust
#      builder stage (arch-adaptive: arm64 and amd64 each get a native binary,
#      ADR-005 D6/D11). Pinned to v0.4.0.
#   2. dcg-wiring (install_cmd) — provisions the dcg-guard wrapper engine + cage config
#      + sentinel fixture at their root-owned, agent-unwritable dest paths (ADR-025 D3).
#      All written chown root:root so the agent cannot overwrite or weaken the guard.
#      Also installs examples/dcg/smoke.sh as /usr/local/lib/rip-cage/recipe-tests/dcg-smoke.sh
#      root:root so the generic name-free runner can execute it (ADR-027 D1).
#
# How DCG works in the cage:
#   - The managed-settings.json PreToolUse hook invokes /usr/local/lib/rip-cage/bin/dcg-guard
#     for EVERY Bash tool call.
#   - dcg-guard (the ENGINE, root-owned via recipe wiring):
#       - cd to a root-owned dir so DCG never walks up to /workspace for project config
#       - sets DCG_CONFIG to the cage-owned config, suppressing the agent-writable user layer
#       - strips DCG_* override env vars that could weaken policy
#       - exec-s /usr/local/bin/dcg (the binary installed by the dcg entry)
#   - Without this recipe, dcg is absent; dcg-guard will error and fail-open (non-blocking).
#
# Agentic composition model (ADR-005 D12, "built for the agentic era"):
#   An agent reads this recipe, copies the tools[] entries into ~/.config/rip-cage/tools.yaml,
#   and runs \`rc build\`. The agent does the wiring; rip-cage provides the seam and recipe.
#   No installer, no auto-wire mechanism, no rc source edit required.
#
# GENERATED by examples/dcg/build-fragment.sh from the canonical source artifacts
# (dcg/dcg-guard, dcg/default-config.toml, tests/fixtures/ripcage-testsentinel-rule.yaml,
# examples/dcg/smoke.sh).
# Do not hand-edit the base64 blobs — edit the source files and re-run the generator.
#
# egress: [] — DCG opens zero external connections (local guard only).

tools:
  # ---------------------------------------------------------------------------
  # TOOL entry 1: build the dcg binary from source (arch-adaptive, pinned tag).
  # ---------------------------------------------------------------------------
  - name: dcg
    archetype: TOOL
    # Pinned to v0.4.0 — the same tag used by the removed Dockerfile rust-builder stage.
    version_pin: "v0.4.0"
    egress: []
    build_source:
      # rust:1-slim-trixie matches the removed rust-builder stage — same toolchain, no compat issues.
      builder_image: "rust:1-slim-trixie"
      build_script: "tests/fixtures/build-dcg-from-source.sh"
      # output_path: the binary produced inside the builder stage; copied to /usr/local/bin/dcg
      # in the runtime image via COPY --from=rc-builder-dcg.
      output_path: "/usr/local/bin/dcg"
    mounts: []

  # ---------------------------------------------------------------------------
  # TOOL entry 2: provision the dcg engine wiring root-owned (guard + config + sentinel + smoke test).
  # install_cmd runs as root in the runtime stage (RUN). It:
  #   - writes /usr/local/lib/rip-cage/bin/dcg-guard (the ENGINE wrapper; ADR-025 D3),
  #     root:root mode 0755 — the agent can execute but cannot replace it.
  #   - writes /usr/local/lib/rip-cage/dcg/config.toml (cage-owned DCG config; ADR-025 D5),
  #     root:root mode 0644 — the agent can read but cannot overwrite.
  #   - writes /usr/local/lib/rip-cage/dcg/fixtures/ripcage-testsentinel-rule.yaml
  #     (sentinel fixture; ADR-025 D1), root:root mode 0644.
  #   - writes /usr/local/lib/rip-cage/recipe-tests/dcg-smoke.sh (behavioral smoke test),
  #     root:root mode 0755 — installed by root, dir+file root-owned (ADR-027 D1).
  # No apt packages needed; the leading ':' is a no-op so the rc-generated
  # 'apt-get update && <install_cmd> && rm ...' wrapper stays valid.
  - name: dcg-wiring
    archetype: TOOL
    version_pin: "bundled-recipe"
    required: true
    assert_loaded: "test -x /usr/local/lib/rip-cage/bin/dcg-guard && test -f /usr/local/lib/rip-cage/dcg/config.toml"
    install_cmd: ": && mkdir -p /usr/local/lib/rip-cage/bin /usr/local/lib/rip-cage/dcg/fixtures /usr/local/lib/rip-cage/recipe-tests && echo '${GUARD_B64}' | base64 -d > /usr/local/lib/rip-cage/bin/dcg-guard && chown root:root /usr/local/lib/rip-cage/bin/dcg-guard && chmod 0755 /usr/local/lib/rip-cage/bin/dcg-guard && echo '${CONFIG_B64}' | base64 -d > /usr/local/lib/rip-cage/dcg/config.toml && chown root:root /usr/local/lib/rip-cage/dcg/config.toml && chmod 0644 /usr/local/lib/rip-cage/dcg/config.toml && echo '${SENTINEL_B64}' | base64 -d > /usr/local/lib/rip-cage/dcg/fixtures/ripcage-testsentinel-rule.yaml && chown root:root /usr/local/lib/rip-cage/dcg/fixtures/ripcage-testsentinel-rule.yaml && chmod 0644 /usr/local/lib/rip-cage/dcg/fixtures/ripcage-testsentinel-rule.yaml && echo '${SMOKE_B64}' | base64 -d > /usr/local/lib/rip-cage/recipe-tests/dcg-smoke.sh && chown root:root /usr/local/lib/rip-cage/recipe-tests/dcg-smoke.sh && chmod 0755 /usr/local/lib/rip-cage/recipe-tests/dcg-smoke.sh && chown root:root /usr/local/lib/rip-cage/recipe-tests"
    egress: []
    mounts: []
YAML
