#!/usr/bin/env bash
# build-fragment.sh — regenerate manifest-fragment.yaml for the postgres-pgvector recipe.
#
# manifest-fragment.yaml embeds postgres-start.sh and smoke.sh as base64 blobs inside a
# single-line install_cmd (the validator rejects multi-line install_cmd, and the seam has
# no file-copy mechanism for recipes). Those blobs are GENERATED — edit the .sh files,
# then re-run this script. Never hand-edit the base64 in the fragment.
#
# Usage (from the repo root):
#   bash examples/postgres-pgvector/build-fragment.sh
#
# Done when: manifest-fragment.yaml is rewritten and `./rc schema validate` style checks
# pass — verify with:
#   RC_MANIFEST_GLOBAL=examples/postgres-pgvector/manifest-fragment.yaml ./rc build --dry-run

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

START_B64="$(base64 < "$HERE/postgres-start.sh" | tr -d '\n')"
SMOKE_B64="$(base64 < "$HERE/smoke.sh" | tr -d '\n')"

# One line, root context, BEFORE `useradd agent` exists (rc splices install_cmd steps ahead
# of the `# Non-root user` sentinel in cage/Dockerfile) — so nothing here may chown to agent.
# The state_dir mkdir + `chown -R agent:agent` is emitted separately by rc, after useradd.
INSTALL_CMD="mkdir -p /etc/postgresql-common"
INSTALL_CMD+=" && echo ''create_main_cluster = false'' > /etc/postgresql-common/createcluster.conf"
INSTALL_CMD+=" && apt-get install -y --no-install-recommends postgresql-17 postgresql-17-pgvector"
INSTALL_CMD+=" && mkdir -p /usr/local/lib/rip-cage/recipe-tests"
INSTALL_CMD+=" && echo ''${START_B64}'' | base64 -d > /usr/local/lib/rip-cage/postgres-pgvector-start.sh"
INSTALL_CMD+=" && chown root:root /usr/local/lib/rip-cage/postgres-pgvector-start.sh"
INSTALL_CMD+=" && chmod 0755 /usr/local/lib/rip-cage/postgres-pgvector-start.sh"
INSTALL_CMD+=" && echo ''${SMOKE_B64}'' | base64 -d > /usr/local/lib/rip-cage/recipe-tests/postgres-pgvector-smoke.sh"
INSTALL_CMD+=" && chown root:root /usr/local/lib/rip-cage/recipe-tests/postgres-pgvector-smoke.sh"
INSTALL_CMD+=" && chmod 0755 /usr/local/lib/rip-cage/recipe-tests/postgres-pgvector-smoke.sh"
INSTALL_CMD+=" && chown root:root /usr/local/lib/rip-cage/recipe-tests"

cat > "$HERE/manifest-fragment.yaml" <<YAML
version: 1
# postgres-pgvector — composable IN-CAGE-DAEMON recipe (rip-cage-z40e).
#
# GENERATED by examples/postgres-pgvector/build-fragment.sh from postgres-start.sh and
# smoke.sh. Edit those, re-run the generator; never hand-edit the base64 below.
#
# NOT floor, never blessed by default (ADR-005 D12 FIRM): this entry lives in examples/
# only. It is never added to manifest/default-tools.yaml, and no rc source names it.
# To enable it, copy the tools[] entry into ~/.config/rip-cage/tools.yaml and run rc build.
#
# What this recipe provisions:
#   A Postgres 17 + pgvector cluster running as a plain unprivileged process inside ONE
#   cage, so a caged agent can run a DB-backed test suite with no docker in the cage and
#   no change to the containment floor. Same pattern GitHub Actions runner images use.
#
#   install_cmd (build time, root)  — postgresql-17 + postgresql-17-pgvector from Debian
#     trixie main (the cage base image, cage/Dockerfile:13). +87 MiB on the built image,
#     measured (935.5 -> 1022.1 MiB). No third-party apt
#     repo or signing key: trixie main carries postgresql-17 17.11 and
#     postgresql-17-pgvector 0.8.0 for both arm64 and amd64. Use PGDG only if you need a
#     version trixie does not ship. Also disables postgresql-common's default "main"
#     cluster (it would sit unused on the same port) and bakes the launcher + smoke test.
#   start   — the launcher at its root-owned path, prefixed with exec. That prefix is LOAD-BEARING:
#     init records the backgrounded job's PID as the daemon PID and later liveness-checks it
#     with kill -0. Without exec, bash forks a wrapper shell, the recorded PID is the
#     WRAPPER, and the wrapper outlives a crashed postmaster — so a dead cluster reports
#     healthy forever and init never restarts it. Measured in a live cage (rip-cage-z40e);
#     a daemon whose start is a SCRIPT PATH hits this, a simple command does not.
#     Runs as the agent user; initdbs on first start only.
#   health  — polls pg_isready inside the probe's own 5s budget, so a first boot that
#     includes initdb does not earn a spurious fail-warn WARNING. -U/-d are named so the
#     probe does not default to the OS user's name for both and log a FATAL on every
#     check — noise that reads like a real fault to whoever opens the daemon log next.
#   state_dir — PGDATA. Cage-lifetime, wiped on rc destroy (in-cage-daemon.md:40).
#     For a cluster that survives destroy, point it under /workspace instead — that is a
#     one-line change here and nowhere else, which is why initdb runs at first start
#     rather than being baked into the image (see README.md).
#
# egress: [] — the cluster binds 127.0.0.1 inside one cage's network namespace. This
# recipe adds NO host to any allowlist and requires no .rip-cage.yaml edit.
#
# How a consuming project selects the in-cage DSN:
#   export DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/test
# Trust auth ignores the password, so that is shape-identical to a typical
# docker-compose DSN with the service host swapped for loopback — no code change in the
# project, and its host compose path is untouched. See README.md.
tools:
  - name: postgres-pgvector
    archetype: IN-CAGE-DAEMON
    version_pin: "17.11+pgvector0.8.0"
    install_cmd: '${INSTALL_CMD}'
    start: "exec /usr/local/lib/rip-cage/postgres-pgvector-start.sh"
    health: "timeout 4 bash -c 'until /usr/lib/postgresql/17/bin/pg_isready -q -h 127.0.0.1 -p 5432 -U postgres -d test; do sleep 0.25; done'"
    state_dir: "/var/lib/rip-cage-daemon/postgres-pgvector"
    egress: []
    mounts: []
YAML

echo "Regenerated $HERE/manifest-fragment.yaml"
echo "  postgres-start.sh -> ${#START_B64} b64 chars"
echo "  smoke.sh          -> ${#SMOKE_B64} b64 chars"
