#!/usr/bin/env bash
# build-fragment.sh — regenerate examples/claude/manifest-fragment.yaml from the
# canonical recipe source artifacts (claude-session-wrapper.sh, managed-settings.json,
# cage-claude.md).
#
# The manifest fragment is self-contained (a user copies it into tools.yaml and
# runs `rc build` with ZERO rc source edits). The recipe provisions the session
# wrapper + managed-settings floor-lock + cage-topology doc into the image via
# a single-line, base64-encoded install_cmd (injection-safe — no newlines reach
# the Dockerfile).
#
# This generator exists only so the artifacts stay human-readable/editable in
# version control; the COMMITTED manifest-fragment.yaml is the load-bearing,
# copy-pasteable recipe. Re-run this after editing any source artifact:
#   examples/claude/build-fragment.sh > examples/claude/manifest-fragment.yaml
#
# rip-cage-wlwc.2.2 (CC migrated from hardcoded Dockerfile bake to composable recipe;
# managed-settings floor-lock preserved via root-owned install_cmd provisioning).
set -euo pipefail

_here="$(cd "$(dirname "$0")" && pwd)"

b64() { base64 < "$1" | tr -d '\n'; }

WRAPPER_B64="$(b64 "${_here}/claude-session-wrapper.sh")"
MANAGED_B64="$(b64 "${_here}/managed-settings.json")"
CAGEMD_B64="$(b64 "${_here}/cage-claude.md")"

cat <<YAML
version: 1
tools:
  # claude (session-wrapper + managed-settings floor-lock) recipe — copy this entry
  # into your tools.yaml to run Claude Code inside rip-cage with:
  #   - per-session config isolation (claude-session-wrapper.sh)
  #   - DCG floor-lock via /etc/claude-code/managed-settings.json (root-owned,
  #     auto-loaded by CC as the highest-precedence settings layer — agent cannot
  #     edit or unregister the hooks baked here; rip-cage-r9n4, ADR-027 D3).
  #   - cage-topology doc at /etc/rip-cage/cage-claude.md
  # After adding, run: rc build
  #
  # GENERATED by examples/claude/build-fragment.sh from the canonical source
  # artifacts (claude-session-wrapper.sh, managed-settings.json, cage-claude.md).
  # Do not hand-edit the base64 blobs — edit the source files and re-run the generator.
  #
  # claude-recipe (TOOL): bakes the CC launch wrapper + managed-settings floor-lock +
  # cage-topology doc into the image at build time, ALL root-owned (agent-unwritable).
  # The CC binary itself is installed by the bundled 'claude' TOOL entry (Dockerfile
  # npm install — stays in the base image).
  #
  # FLOOR-LOCK SLOT (rip-cage-r9n4 / ADR-027 D3 / ADR-002 D5):
  #   /etc/claude-code/managed-settings.json is CC's managed-settings path — hooks
  #   here merge un-suppressibly with user/project hooks and PreToolUse is deny-wins.
  #   This delivers the DCG guard hook via a layer the in-cage agent CANNOT edit or
  #   unregister. MUST stay root-owned at a root-owned path. Parent /etc/claude-code
  #   must also be root-owned (unix-dir-ownership-is-the-write-gate principle).

  # ---------------------------------------------------------------------------
  # TOOL entry: bake the CC wrapper + managed-settings + cage doc (root-owned).
  # install_cmd runs as root in the runtime stage (RUN). It:
  #   - writes /usr/local/bin/claude (the session-isolation wrapper; precedes /usr/bin/claude
  #     on PATH), root:root mode 0755 — agent can execute but cannot replace it.
  #   - creates /etc/claude-code/ (root-owned dir — parent ownership is the write gate),
  #     writes /etc/claude-code/managed-settings.json (floor-lock slot; ADR-027 D3),
  #     root:root mode 0644 — agent can read but cannot overwrite.
  #   - writes /etc/rip-cage/cage-claude.md (cage-topology doc),
  #     root:root mode 0644 — agent can read but cannot overwrite.
  # No apt packages needed; the leading ':' is a no-op so the rc-generated
  # 'apt-get update && <install_cmd> && rm ...' wrapper stays valid.
  - name: claude-recipe
    archetype: TOOL
    version_pin: "bundled-recipe"
    install_cmd: ": && mkdir -p /etc/rip-cage && echo '${WRAPPER_B64}' | base64 -d > /usr/local/bin/claude && chown root:root /usr/local/bin/claude && chmod 0755 /usr/local/bin/claude && mkdir -p /etc/claude-code && chown root:root /etc/claude-code && chmod 0755 /etc/claude-code && echo '${MANAGED_B64}' | base64 -d > /etc/claude-code/managed-settings.json && chown root:root /etc/claude-code/managed-settings.json && chmod 0644 /etc/claude-code/managed-settings.json && echo '${CAGEMD_B64}' | base64 -d > /etc/rip-cage/cage-claude.md && chown root:root /etc/rip-cage/cage-claude.md && chmod 0644 /etc/rip-cage/cage-claude.md"
    egress: []
    mounts: []
YAML
