#!/usr/bin/env bash
# build-fragment.sh — regenerate examples/pi/manifest-fragment.yaml from the
# canonical recipe source artifacts (pi-wrapper.sh, dcg-gate.ts, cage-pi.md).
#
# The manifest fragment is self-contained (a user copies it into tools.yaml and
# runs `rc build` with ZERO rc source edits). The recipe bakes the launch wrapper
# + guard extension + cage-topology doc into the image via a single-line,
# base64-encoded install_cmd (injection-safe — no newlines reach the Dockerfile).
#
# This generator exists only so the artifacts stay human-readable/editable in
# version control; the COMMITTED manifest-fragment.yaml is the load-bearing,
# copy-pasteable recipe. Re-run this after editing any source artifact:
#   examples/pi/build-fragment.sh > examples/pi/manifest-fragment.yaml
#
# rip-cage-wlwc.2.2 (AGENT seam migration — pi as a swappable example recipe).
set -euo pipefail

_here="$(cd "$(dirname "$0")" && pwd)"

b64() { base64 < "$1" | tr -d '\n'; }

WRAPPER_B64="$(b64 "${_here}/pi-wrapper.sh")"
GATE_B64="$(b64 "${_here}/dcg-gate.ts")"
CAGEMD_B64="$(b64 "${_here}/cage-pi.md")"

cat <<YAML
version: 1
tools:
  # pi (DCG-guarded) recipe — copy this entry into your tools.yaml
  # to run the pi coding agent inside rip-cage WITH the default-on DCG command
  # guard. After adding, run: rc build
  #
  # GENERATED by examples/pi/build-fragment.sh from the canonical source
  # artifacts (pi-wrapper.sh, dcg-gate.ts, cage-pi.md). Do not hand-edit the
  # base64 blobs — edit the source files and re-run the generator.
  #
  # pi-recipe (TOOL): bakes the launch wrapper + DCG guard extension +
  # cage-topology doc into the image at build time, ALL root-owned
  # (agent-unwritable — the guard cannot be self-disabled in the ro-default
  # config; ADR-027 D1, ADR-005 D11). The pi BINARY itself is installed
  # by the bundled 'pi' TOOL entry (Dockerfile npm install).
  #
  # SWAPPABLE GUARD: the DCG guard is the wrapper's '--no-extensions -e dcg-gate.ts'
  # wiring. To run pi with ALL its extensions and NO dcg-gate, swap THIS recipe for
  # examples/pi/manifest-fragment-no-guard.yaml — ZERO rc source edits.

  # ---------------------------------------------------------------------------
  # TOOL entry: bake the pi launch wrapper + guard extension + cage doc (root-owned).
  # install_cmd runs as root in the runtime stage (RUN). It:
  #   - writes /usr/local/bin/pi  (the launch wrapper; precedes /usr/bin/pi on PATH),
  #     root:root mode 0755 — the agent can execute but cannot replace it.
  #   - writes /home/agent/.pi/agent/extensions/dcg-gate.ts (the DCG guard),
  #     and root-owns the extensions/ dir so the agent cannot add a competing
  #     extension or overwrite the guard (rip-cage-olen protection, preserved).
  #   - writes /etc/rip-cage/cage-pi.md (cage-topology doc, consumed generically
  #     by init-rip-cage.sh).
  # No apt packages needed; the leading ':' is a no-op so the rc-generated
  # 'apt-get update && <install_cmd> && rm ...' wrapper stays valid.
  - name: pi-recipe
    archetype: TOOL
    version_pin: "bundled-recipe"
    install_cmd: ": && mkdir -p /home/agent/.pi/agent/extensions /etc/rip-cage && echo '${WRAPPER_B64}' | base64 -d > /usr/local/bin/pi && chown root:root /usr/local/bin/pi && chmod 0755 /usr/local/bin/pi && echo '${GATE_B64}' | base64 -d > /home/agent/.pi/agent/extensions/dcg-gate.ts && chown root:root /home/agent/.pi/agent/extensions/dcg-gate.ts && chmod 0644 /home/agent/.pi/agent/extensions/dcg-gate.ts && chown root:root /home/agent/.pi/agent/extensions && chmod 0755 /home/agent/.pi/agent/extensions && echo '${CAGEMD_B64}' | base64 -d > /etc/rip-cage/cage-pi.md && chown root:root /etc/rip-cage/cage-pi.md && chmod 0644 /etc/rip-cage/cage-pi.md"
    egress: []
    mounts: []
YAML
