#!/usr/bin/env bash
# build-fragment.sh — regenerate examples/pi/manifest-fragment.yaml from the
# canonical recipe source artifacts (pi-wrapper.sh, cage-pi.md).
#
# rip-cage-l72i.1 (ADR-027 D4): the pi recipe NO LONGER bakes dcg-gate.ts or
# the launch wrapper. Both have been relocated:
#   - dcg-gate.ts  → examples/dcg/manifest-fragment.yaml (dcg-wiring entry)
#   - wrapper/launch flags → assembled by rc build from manifest launch_args
#
# The pi recipe now only bakes:
#   - /etc/rip-cage/ directory structure
#   - /etc/rip-cage/cage-pi.md (cage-topology doc)
# The wrapper and guard wiring are assembled by rc build from the composed
# fragments' launch_args declarations (ADR-027 D4 / ADR-005 D12).
#
# The manifest fragment is self-contained (a user copies it into tools.yaml and
# runs `rc build` with ZERO rc source edits). The recipe bakes the
# cage-topology doc into the image via a single-line, base64-encoded install_cmd
# (injection-safe — no newlines reach the Dockerfile).
#
# This generator exists only so the artifacts stay human-readable/editable in
# version control; the COMMITTED manifest-fragment.yaml is the load-bearing,
# copy-pasteable recipe. Re-run this after editing any source artifact:
#   examples/pi/build-fragment.sh > examples/pi/manifest-fragment.yaml
#
# rip-cage-wlwc.2.2 (AGENT seam migration — pi as a swappable example recipe).
set -euo pipefail

_here="$(cd "$(dirname "$0")" && pwd)"

b64() { base64 < "$1" | tr -d '\n'; }

CAGEMD_B64="$(b64 "${_here}/cage-pi.md")"

cat <<YAML
version: 1
tools:
  # pi recipe — copy this entry into your tools.yaml and run: rc build
  #
  # GENERATED by examples/pi/build-fragment.sh from the canonical source
  # artifact (cage-pi.md). Do not hand-edit the base64 blob — edit the
  # source file and re-run the generator.
  #
  # pi-recipe (TOOL): bakes the cage-topology doc into the image at build time.
  # The pi BINARY itself is installed by the bundled 'pi' TOOL entry (Dockerfile
  # npm install). The pi launch shim (/usr/local/bin/pi) and its args are
  # assembled by rc build from the launch_args declared across composed recipe
  # fragments (ADR-027 D4 / rip-cage-l72i.1) — not baked by this recipe.
  #
  # To get DCG guard wiring, ALSO compose examples/dcg/manifest-fragment.yaml.
  # The DCG fragment bakes dcg-gate.ts AND contributes the launch_args
  # (-e /etc/rip-cage/pi/dcg-gate.ts). OPEN by default (ADR-027 D1, FIRM
  # 2026-07-02): no --no-extensions, so pi's own extension auto-discovery
  # paths stay live even with DCG composed (see examples/dcg/README.md for
  # the LOCKED opt-in variant). Composing WITHOUT the DCG fragment gives a
  # clean generic shim with no guard and auto-discovery on.
  #
  # ADR-005 D12: the pi recipe no longer names dcg (the launch wiring is now
  # declared in the fragment that contributes it — the dcg recipe).
  #
  # OPTIONAL: pin pi's provider/model via launch_args (rip-cage-p35a.3 —
  # MECHANISM ONLY; closes rip-cage-tl6q's pin-mechanism conjunct — the
  # construction-skill VALUE-CHOICE conjunct closes at rip-cage-p35a.5).
  # Throttle rationale (rip-cage-px6v spike, live-verified 2026-07-02): pi's
  # HEADLESS default resolves to the Claude subscription entitlement, which
  # is throttled by Anthropic's third-party-app usage policy (400 "Third-party
  # apps now draw from your extra usage"). This throttle is independent of
  # interactive/headless/herdr-spawned launch mode — pinning a working
  # provider/model forces every launch shape onto it.
  # NOT enabled by default here — do NOT uncomment this in a shipped/default
  # manifest. Forcing one provider on EVERY operator would break anyone
  # without that provider's auth AND override pi's interactive-picked
  # default for users who never hit the throttle (DESIGN CLARIFICATION,
  # orchestrator 2026-07-02). This is a mechanism + a worked EXAMPLE — the
  # operator (or the construction skill, rip-cage-p35a.4/.5) chooses the
  # actual value for THEIR auth. To pin, add a launch_args field to a TOOL
  # entry that contributes to the pi shim assembly (any composed fragment;
  # this one is a natural home since it already provisions pi's lifecycle):
  #
  #   launch_args: ["--model", "openai-codex/gpt-5.5"]  # EXAMPLE — set this to YOUR provider/model + auth
  #
  # (spike-verified working value: openai-codex/gpt-5.5 on a ChatGPT-account
  # codex login; -codex/-codex-mini model-name variants are rejected for
  # ChatGPT accounts — see rip-cage-px6v spike notes.)

  # ---------------------------------------------------------------------------
  # TOOL entry: bake the cage-topology doc into the image (root-owned).
  # install_cmd runs as root in the runtime stage (RUN). It:
  #   - creates /etc/rip-cage/ directory structure
  #   - writes /etc/rip-cage/cage-pi.md (cage-topology doc, consumed generically
  #     by init-rip-cage.sh)
  # No apt packages needed; the leading ':' is a no-op so the rc-generated
  # 'apt-get update && <install_cmd> && rm ...' wrapper stays valid.
  # 'init' agent-context boot-hook (rip-cage-p35a.3, seam from rip-cage-p35a.2 /
  # ADR-005 D7): relocated here from init-rip-cage.sh (commit e360c3b, the
  # rip-cage-fwp3 stopgap). herdr v0.7.0's 'integration install pi' (run by the
  # herdr multiplexer start hook, examples/herdr/manifest-fragment.yaml) writes
  # into \${PI_CODING_AGENT_DIR}/extensions/ and REQUIRES that directory to
  # already exist — it does not create it. Must run AS AGENT (no sudo; the
  # TOOL init hook seam is agent-context-only) — creating it at build time as
  # root reintroduces the Permission-denied bug from the 2026-06-29 audit.
  # Fail-loud WARNING (not fail-closed) on mkdir failure, matching the
  # original stopgap's semantics (ADR-005 D10 fail-warn asymmetry for user
  # tool contributions) — a silently-absent extensions/ dir would resurrect
  # this bead's exact "extension directory not found" symptom with zero
  # signal. Firing is now gated on THIS recipe being composed (not on
  # \`command -v pi\`, which was always true anyway since pi is npm-installed
  # unconditionally in the base Dockerfile) — a cleanup win: the old gate was
  # vestigial.
  - name: pi-recipe
    archetype: TOOL
    version_pin: "bundled-recipe"
    init: '_rc_pi_ext_dir="\${PI_CODING_AGENT_DIR:-/home/agent/.pi/agent}/extensions"; if ! mkdir -p "\$_rc_pi_ext_dir" 2>/tmp/rc-pi-ext-mkdir-err; then echo "[rip-cage] WARNING: could not create \${_rc_pi_ext_dir} (herdr''s boot-time ''integration install pi'' will fail with ''extension directory not found'', rip-cage-fwp3): \$(cat /tmp/rc-pi-ext-mkdir-err 2>/dev/null)" >&2; fi; rm -f /tmp/rc-pi-ext-mkdir-err; true'
    install_cmd: ": && mkdir -p /etc/rip-cage/pi /etc/rip-cage && echo '${CAGEMD_B64}' | base64 -d > /etc/rip-cage/cage-pi.md && chown root:root /etc/rip-cage/cage-pi.md && chmod 0644 /etc/rip-cage/cage-pi.md"
    egress: []
    mounts: []
YAML
