#!/usr/bin/env bash
# build-fragment.sh — regenerate examples/pi/manifest-fragment.yaml from the
# canonical recipe source artifacts (pi-wrapper.sh, cage-pi.md).
#
# rip-cage-l72i.1 (ADR-027 D4): the pi recipe NO LONGER bakes dcg-gate.ts or
# the launch wrapper. Both have been relocated:
#   - dcg-gate.ts  → examples/dcg/manifest-fragment.yaml (dcg-wiring entry)
#   - wrapper/launch flags → assembled by rc build from manifest launch_args
#
# The pi recipe now only bakes:
#   - /etc/rip-cage/ directory structure
#   - /etc/rip-cage/cage-pi.md (cage-topology doc)
# The wrapper and guard wiring are assembled by rc build from the composed
# fragments' launch_args declarations (ADR-027 D4 / ADR-005 D12).
#
# The manifest fragment is self-contained (a user copies it into tools.yaml and
# runs `rc build` with ZERO rc source edits). The recipe bakes the
# cage-topology doc into the image via a single-line, base64-encoded install_cmd
# (injection-safe — no newlines reach the Dockerfile).
#
# This generator exists only so the artifacts stay human-readable/editable in
# version control; the COMMITTED manifest-fragment.yaml is the load-bearing,
# copy-pasteable recipe. Re-run this after editing any source artifact:
#   examples/pi/build-fragment.sh > examples/pi/manifest-fragment.yaml
#
# rip-cage-wlwc.2.2 (AGENT seam migration — pi as a swappable example recipe).
set -euo pipefail

_here="$(cd "$(dirname "$0")" && pwd)"

b64() { base64 < "$1" | tr -d '\n'; }

CAGEMD_B64="$(b64 "${_here}/cage-pi.md")"

cat <<YAML
version: 1
tools:
  # pi recipe — copy this entry into your tools.yaml and run: rc build
  #
  # GENERATED by examples/pi/build-fragment.sh from the canonical source
  # artifact (cage-pi.md). Do not hand-edit the base64 blob — edit the
  # source file and re-run the generator.
  #
  # pi-recipe (TOOL): bakes the cage-topology doc into the image at build time.
  # The pi BINARY itself is installed by the bundled 'pi' TOOL entry (Dockerfile
  # npm install). The pi launch shim (/usr/local/bin/pi) and its args are
  # assembled by rc build from the launch_args declared across composed recipe
  # fragments (ADR-027 D4 / rip-cage-l72i.1) — not baked by this recipe.
  #
  # To get DCG guard wiring, ALSO compose examples/dcg/manifest-fragment.yaml.
  # The DCG fragment bakes dcg-gate.ts AND contributes the launch_args
  # (--no-extensions -e /etc/rip-cage/pi/dcg-gate.ts). Composing WITHOUT the
  # DCG fragment gives a clean generic shim with no guard and auto-discovery on.
  #
  # ADR-005 D12: the pi recipe no longer names dcg (the launch wiring is now
  # declared in the fragment that contributes it — the dcg recipe).

  # ---------------------------------------------------------------------------
  # TOOL entry: bake the cage-topology doc into the image (root-owned).
  # install_cmd runs as root in the runtime stage (RUN). It:
  #   - creates /etc/rip-cage/ directory structure
  #   - writes /etc/rip-cage/cage-pi.md (cage-topology doc, consumed generically
  #     by init-rip-cage.sh)
  # No apt packages needed; the leading ':' is a no-op so the rc-generated
  # 'apt-get update && <install_cmd> && rm ...' wrapper stays valid.
  - name: pi-recipe
    archetype: TOOL
    version_pin: "bundled-recipe"
    install_cmd: ": && mkdir -p /etc/rip-cage/pi /etc/rip-cage && echo '${CAGEMD_B64}' | base64 -d > /etc/rip-cage/cage-pi.md && chown root:root /etc/rip-cage/cage-pi.md && chmod 0644 /etc/rip-cage/cage-pi.md"
    egress: []
    mounts: []
YAML
